/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_kakao_ffmpegjniexample_NDK */

#ifndef _Included_com_example_kakao_ffmpegjniexample_NDK
#define _Included_com_example_kakao_ffmpegjniexample_NDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_kakao_ffmpegjniexample_NDK
 * Method:    run_ffmpeg
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_kakao_ffmpegjniexample_NDK_run_1ffmpeg
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
